# Generated by Django 3.0.2 on 2020-02-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0001_initial'),
        ('poll', '0002_auto_20200228_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='users',
            field=models.ManyToManyField(to='organize.user'),
        ),
    ]
