# Generated by Django 3.0.2 on 2020-03-07 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0001_initial'),
        ('poll', '0003_poll_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pollchoice',
            fields=[
                ('poll_choice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='poll',
            name='users',
        ),
        migrations.AlterField(
            model_name='poll',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Pollvote',
            fields=[
                ('vote_id', models.IntegerField(primary_key=True, serialize=False)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll')),
                ('poll_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Pollchoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organize.user')),
            ],
        ),
        migrations.AddField(
            model_name='pollchoice',
            name='polls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll'),
        ),
    ]
