# Generated by Django 3.0.2 on 2020-03-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0030_auto_20200309_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
