# Generated by Django 3.0.2 on 2020-03-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0031_auto_20200309_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='start_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
