# Generated by Django 3.0.2 on 2020-03-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0033_auto_20200309_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='start_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
