# Generated by Django 3.0.2 on 2020-03-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0045_auto_20200311_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
