# Generated by Django 3.0.2 on 2020-03-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_poll_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='users',
        ),
    ]
