# Generated by Django 3.0.2 on 2020-03-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_poll_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
