# Generated by Django 3.0.2 on 2020-03-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_auto_20200308_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollchoice',
            name='polls',
        ),
        migrations.RemoveField(
            model_name='pollvote',
            name='poll',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
