# Generated by Django 3.0.2 on 2020-03-08 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0001_initial'),
        ('poll', '0018_auto_20200308_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organize.User'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.RemoveField(
            model_name='pollchoice',
            name='polls',
        ),
        migrations.AddField(
            model_name='pollchoice',
            name='polls',
            field=models.ManyToManyField(to='poll.Poll'),
        ),
        migrations.AlterField(
            model_name='pollvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organize.User'),
        ),
    ]
