# Generated by Django 3.0.2 on 2020-03-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0034_auto_20200309_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
