# Generated by Django 3.0.2 on 2020-03-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0035_poll_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
