# Generated by Django 3.0.2 on 2020-03-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0037_auto_20200310_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
