# Generated by Django 3.0.2 on 2020-03-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0039_auto_20200310_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
