# Generated by Django 3.0.2 on 2020-03-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0044_auto_20200311_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
