# Generated by Django 3.0.2 on 2020-03-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0046_auto_20200311_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
